### PR TITLE
Tutorial on Pandas task 1

### PR DESCRIPTION
**Pull request by vishnubalaji**

### CODE REVIEW

**Comment by amezng** [comment]
This is not working. Check it and re-submit the PR
Error : `Expected corresponding JSX closing tag for <br>`

**Comment by amezng** [comment]
Add the code, above the Objective to fix it. 
```
import Gist from "react-gist"
```
- Also use dark mode for taking screenshot of the code for better readability. 
- Delete the redundant image for showing environment activation status
- Minify the PNG files using online tools.

**Comment by vishnubalaji** [comment]
Okay sir. Making the changes

**Comment by vishnubalaji** [comment]
I have included the changes mentioned.

**Comment by amezng** [comment]
@vishnubalaji  The build is failing. Can you check and fix it?

**Comment by amezng** [comment]
og-jupyter-vscode-pandas
Also use this as the image in the header, instead of `/img/tutorial/shared/og-spark.png`

**Comment by vishnubalaji** [comment]
okay sir, I am looking into it.

**Comment by vishnubalaji** [comment]
Extension is getting changed to the uppercase one, I will try to change it here in my local machine and commit again.

**Comment by vishnubalaji** [comment]
I have updated the pull request

**Pull request merged**
